openapi: 3.0.3
info:
  title: AllFileConvert - Upload API
  version: 1.0.0
  description: 파일 업로드 서비스

paths:
  /upload:
    post:
      summary: 파일 업로드
      description: 클라이언트로부터 파일을 업로드 받습니다.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                type: string
                format: binary
                description: 업로드할 파일
      response:
        '200':
          description: 업로드 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  file_id:
                    type: string
                    example: "1c23dd8e-c872-46ab-b1d2-66b2a0cd3c82"
        '400':
          description: 잘못된 요청 (파일 누락 등)
        '500':
          description: 서버 오류