name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  backend-upload:
    name: Backend - Upload Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/upload
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install deps
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

  backend-convert:
    name: Backend - Convert Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/convert
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install deps
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

  backend-download:
    name: Backend - Download Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/download
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install deps
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...